cities:
- id: 1
  name: Islamabad
- id: 2
  name: Lahore
- id: 3
  name: Rawalpindi
- id: 166
  name: Taxila
- id: 167
  name: Murree
- id: 168
  name: Multan
- id: 169
  name: Karachi
- id: 170
  name: Faisalabad
- id: 171
  name: Mardan
- id: 172
  name: Sargodha
- id: 173
  name: Wah
- id: 174
  name: Gujranwala
- id: 175
  name: Bahawalpur
- id: 176
  name: Peshawar
- id: 177
  name: Chakwal
- id: 178
  name: Talagang
- id: 179
  name: Gwadar
- id: 180
  name: Attock
- id: 181
  name: Hasanabdal
- id: 182
  name: Abbottabad
- id: 183
  name: Hyderabad
- id: 184
  name: Gilgit
- id: 185
  name: Khanpur
- id: 186
  name: Sheikhupura
- id: 187
  name: Quetta
- id: 188
  name: Daska
- id: 189
  name: Dera Ghazi Khan
- id: 190
  name: Sialkot
- id: 191
  name: Kashmir
- id: 192
  name: Mirpur (Azad Kashmir)
- id: 193
  name: Jhelum
- id: 194
  name: Okara
- id: 195
  name: Nowshera
- id: 196
  name: Fateh Jhang
- id: 197
  name: Charsadda
- id: 198
  name: Swabi
- id: 199
  name: Kohat
- id: 200
  name: Karak
- id: 201
  name: Bannu
- id: 202
  name: Hangu
- id: 203
  name: DI Khan
- id: 204
  name: Tank
- id: 205
  name: Lakki Marwat
- id: 206
  name: Swat
- id: 207
  name: Sukkur
- id: 208
  name: Malakand PA
- id: 209
  name: Shangla
- id: 210
  name: Dir Upper
- id: 211
  name: Dir Lower
- id: 212
  name: Chitral
- id: 213
  name: Buner
- id: 214
  name: Haripur
- id: 215
  name: Mansehra
- id: 216
  name: Kohistan
- id: 217
  name: Torghar
- id: 218
  name: Batgram
- id: 219
  name: Muzaffarabad
- id: 220
  name: Kotli
- id: 221
  name: Bagh
- id: 222
  name: Haveli
- id: 223
  name: Poonch
- id: 224
  name: Sudhanoti
- id: 225
  name: Neelam
- id: 226
  name: Hunza
- id: 227
  name: Skardu
- id: 228
  name: Ghanche
- id: 229
  name: Bhimber
- id: 230
  name: Sarai Alamgir
- id: 232
  name: Nawabshah
- id: 233
  name: Gujrat
- id: 234
  name: Lalamusa
- id: 235
  name: Kharian
- id: 236
  name: Wazirabad
- id: 240
  name: Khanewal
- id: 241
  name: Gujar Khan
- id: 243
  name: Dina
- id: 244
  name: Mangla
- id: 273
  name: Kasur
- id: 306
  name: Sahiwal
- id: 339
  name: Sadiqabad
